##[>] 🤖🤖
spec:
  inputs:
    profiles:
      type: array
    arches:
      type: array
      default: [amd64, arm64]
    image:
      type: string
      default: $CI_IMAGE
    tags:
      type: array
      default: [gke-linux-$ARCH-small]
    enabled:
      type: string
      default: "true"
    as_user:
      type: string
      default: "true"
      options: ["true", "false"]
    stage:
      type: string
      default: dry-run-apply
    name:
      type: string
      default: dry-run-apply-linux
---
"$[[ inputs.name ]]":
  extends: .che-profile-matrix-$[[ inputs.as_user ]]
  stage: $[[ inputs.stage ]]
  image: $[[ inputs.image ]]
  tags: $[[ inputs.tags ]]
  needs: []
  parallel:
    matrix:
      - CHE_PROFILE: $[[ inputs.profiles ]]
        ARCH: $[[ inputs.arches ]]
  variables:
    MK_DRY_RUN: all
  rules:
    - if: '"$[[ inputs.enabled ]]" != "true"'
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
##[<] 🤖🤖
