##[>] 🤖🤖
.TriggerAutomation:
  interruptible: false
  inherit:
    variables: false
  variables:
    AUTOMATION_EVENT: '{"type":"$EVENT_TYPE","source":{"project":"$CI_PROJECT_PATH","pipeline":"$CI_PIPELINE_ID","ref":"$CI_COMMIT_REF_NAME","sha":"$CI_COMMIT_SHA"},"details":$EVENT_DETAILS}'
  trigger:
    project: konradodwrot/cross-repo/automation
    branch: main
    forward:
      yaml_variables: true
      pipeline_variables: false
##[<] 🤖🤖
